### ISSUE TITLE
Refactor sounds to enums

### ISSUE THREAD

**Issue by kh498** [inf112-v19/Blodige-roboter#123]
Acceptance criteria: 
- [x] Sounds take a path to a sound file as parameters (and save it ofc)
- [x] Sound is an enum with the method `play()` that plays the sound
- [x] `playActionSound` in `ActionTile` return a sound enum
- [x] The phase plays the sound when action is called

**Comment by kapir** [comment]
Utvikler: @kapir 
Tester: @kh498
