### ISSUE TITLE
Sometimes a laser trail is left by the robot

### ISSUE THREAD

**Issue by kapir** [inf112-v19/Blodige-roboter#137]
Sometimes an old laser trail can be seen on the map after the laser phase

**To Reproduce**
Shoot "robots" in cross, or let robot shoot at another then move the recently shot robot
**Expected behavior**
Map should remove this trail in the cleanLasers job at end of the laserPhase

**Screenshots**
https://files.slack.com/files-pri/TEWHW8R5J-FHHR1DV45/screenshot_2019-04-01_at_15.59.01.png

**Comment by kh498** [comment]
The screenshot does not work
