### ISSUE TITLE
Draw ui over the map (add styrebrett)

### ISSUE THREAD

**Issue by kapir** [inf112-v19/Blodige-roboter#14]
Interaction with [this ](https://raw.githubusercontent.com/wiki/inf112-v19/Blodige-roboter/02-02-2019.jpg)drawing is also included in this issue

Utvikler: @kh498 
Tester: @rikkeaas

**Comment by kapir** [comment]
Postponed to next iteration because of challenges with user interaction in libgdx

**Comment by kh498** [comment]
saved you a click
![bilde](https://user-images.githubusercontent.com/1556738/52526036-23a08000-2cb3-11e9-9218-934867e747f8.png)

**Comment by kh498** [comment]
* Test Direction's right, left and inverse
* Test player damage, heal and kill
* Test Robot move(Movement)
* Test all control panel event listeners get the correct event 
* Test manually
