### ISSUE TITLE
Multiple archive markers on same space

### ISSUE THREAD

**Issue by kh498** [inf112-v19/Blodige-roboter#147]
From the manual (page 8)

>If two or more robots would reenter play on the same space, they’re placed back on the board in the order they were destroyed.The first robot that was destroyed gets the archive space, facing any direction that player chooses.The player whose robot was destroyed next then chooses an empty adjacent space (looking orthogonally OR diagonally) and puts the robot on that space. That robot can face any direction that player chooses, except that there can’t be another robot in its line of sight 3 spaces away or closer.Ignore all board elements except for pits when placing your robot in an adjacent space. You can’t start a turn with your robot in a pit. They suffer enough as it is.

Currently the first robot (ie the robot already on the space) will be destroyed as there can only be one entity on at a given loca

**Comment by kapir** [comment]
Utvikler: @kh498 
Tester: @kapir

**Comment by kh498** [comment]
> there can’t be another robot in its line of sight 3 spaces away or closer.

This is ignored, it will sted try all location within a radius of one (will this be enough radius?)

>Ignore all board elements except for pits when placing your robot in an adjacent space.

This is also not done

 >You can’t start a turn with your robot in a pit. They suffer enough as it is.

I wish I could
