### ISSUE TITLE
Register a flag visit, and have control over how many flag visits a robot has

### ISSUE THREAD

**Issue by kapir** [inf112-v19/Blodige-roboter#21]
Utvikler: @rikkeaas 
Tester: @runalmaas

**Comment by rikkeaas** [comment]
@runalmaas I'm not sure how you can test this code. But you can probably test canGetFlag() and registerFlagVisit() in the player class. My changes in the MapInteractOnUser class are more difficult to test without the rest of the logic, but maybe you can find a way to test it.
