### ISSUE TITLE
Refactor assets

### ISSUE THREAD

**Issue by kh498** [inf112-v19/Blodige-roboter#29]
Create a wiki page on how the assets folder is structure
Change structure it self

**Comment by kh498** [comment]
Code in branch 9-interfaces

**Comment by kh498** [comment]
Wiki created:  [Assets Folder Structure](https://github.com/inf112-v19/Blodige-roboter/wiki/Assets-Folder-Structure)

**Comment by kapir** [comment]
Added in #31
