### ISSUE TITLE
Create enum for sprites

### ISSUE THREAD

**Issue by kh498** [inf112-v19/Blodige-roboter#32]
Create an enum that holds data related to TiledMapTile.
This means that `Entity.getTile()` and `MapHandler.getBoardLayerTile(int,int)` should return this enum.

It should be the common, asset independent, way of refering to tiles and how they react to the environment.

**Comment by kapir** [comment]
See TODO @ [Robot: Line 30](https://github.com/inf112-v19/Blodige-roboter/blob/4f37b3401a66c5132b173c1233a6edfa65f9be47/src/main/java/no/uib/inf112/core/player/Robot.java#L30)

**Comment by kapir** [comment]
Utvikler: @runalmaas 
Tester: @kh498
