### ISSUE TITLE
Create player handler

### ISSUE THREAD

**Issue by kh498** [inf112-v19/Blodige-roboter#33]
To have N number of players on the map at once

**Comment by kapir** [comment]
Dependant on decision regarding #28

**Comment by kapir** [comment]
See FIXME @ [RoboRally:Line33](https://github.com/inf112-v19/Blodige-roboter/blob/4f37b3401a66c5132b173c1233a6edfa65f9be47/src/main/java/no/uib/inf112/core/RoboRally.java#L33)

**Comment by kapir** [comment]
Utvikler: @DanielBerge 
Tester: @rikkeaas
