### ISSUE TITLE
Player should be able to program their registers

### ISSUE THREAD

**Issue by kh498** [inf112-v19/Blodige-roboter#47]
* `N` cards to choose from (based on health)
*  Be able to drag and drop on control panel cards ([see here](https://github.com/libgdx/libgdx/blob/a4805d6a017b80622d6bfdd3a791352257a3c539/tests/gdx-tests/src/com/badlogic/gdx/tests/DragAndDropTest.java))

**Comment by kapir** [comment]
Utvikler: @kh498 
Tester: @kapir
