### ISSUE TITLE
Proper gameround logic

### ISSUE THREAD

**Issue by kapir** [inf112-v19/Blodige-roboter#56]
should work with what @kh498 has done with #47

**Comment by kapir** [comment]
Utvikler: @DanielBerge 
Tester: @runalmaas

**Comment by kapir** [comment]
@DanielBerge are you handling that the deck should be initialized or reset for every round? currently there is no handling of all the cards being drawn in the master branch

**Comment by DanielBerge** [comment]
> @DanielBerge are you handling that the deck should be initialized or reset for every round? currently there is no handling of all the cards being drawn in the master branch

Currently only shuffling the cards. But i will fix it in this issue.
