### ISSUE TITLE
Add ToString() for suitable classes

### ISSUE THREAD

**Issue by kapir** [inf112-v19/Blodige-roboter#60]
Acceptance criteria: For future debugging(why would we need that!?) it could be smart to add some toStrings for those classes this is suitable.
Classes:
ProgramCard
PlayerCard
MovementCard
Player
Cardslot: "Cardslot: {current card}"
Advanced tilemaphandler printing otu the map
Playerhandler
Movementdeck
MapAction
Conveyor "Conveyor: Moves player x from (x,y) to (x,y)"
Robot

**Comment by kh498** [comment]
ProgramCard got a todo in pr #64

**Comment by kapir** [comment]
Utvikler: @RuneThe 
Tester: @kh498
