### ISSUE TITLE
A robot should push another robot when they collide

### ISSUE THREAD

**Issue by kh498** [inf112-v19/Blodige-roboter#65]

**Comment by kapir** [comment]
This should implement a move function in the robot class imo. We also need other movement logic when it comes to conveyor. The robots move logic should also include checking for walls, having a canMove could also help us especially thinking about when pushing a robot we need to check if it can move that direction and then check or else we might have to start throwing exeptions.

**Comment by kh498** [comment]
Fixed in #108
