### ISSUE TITLE
Make title screen

### ISSUE THREAD

**Issue by runalmaas** [inf112-v19/Blodige-roboter#68]
Acceptance criteria:

Title screen must contain buttons for 
* new game - Start a new game
* options - graphics and stuff
* controlls - Show what different buttons do in-game
* credits - Show all people involved and licenses used

It also needs multiplayer and singleplayer buttons, this could be sub menus from "new game".

**Comment by kapir** [comment]
We might want to extend this to be also a setting for the new game, i was thinking that we would postpone this until we have a clearer understanding on how the multiplayer is gonna work.

**Comment by kapir** [comment]
Utvikler: @rikkeaas 
Tester: @runalmaas

**Comment by DanielBerge** [comment]
Decided to change to:
* Single Player
* Join
* Host
* Options
* Quit
