### ISSUE TITLE
Check for holes, walls and robots for each step

### ISSUE THREAD

**Issue by rikkeaas** [inf112-v19/Blodige-roboter#73]
Acceptance criteria: When robots move we should check for holes, walls and other robots for each step they take, i.e. if they try to move more than one step they can't move over a hole or through a wall or robot (nb there is an option card that allows robots to jump over walls). Walls should make the robot not move, this should also happen when being moved by something else e.g. other robot, conveyor or pusher. Robots should be pushed.

**Comment by kapir** [comment]
Sub issue for this: #99

**Comment by kapir** [comment]
Utvikler: @kh498 
Tester: @rikkeaas
