### ISSUE TITLE
Support walls in map

### ISSUE THREAD

**Issue by rikkeaas** [inf112-v19/Blodige-roboter#99]
Acceptance criteria: Robots should not be able to move past walls. They should move to the wall, but not further. F.ex. if the robot tries to move 2 and there is a wall after one step the robot should move one step and then stop. Also robots should move to tiles with a wall if the wall is on the opposite edge from where the robot is coming from.

**Comment by kapir** [comment]
Part of #73. Its fine to have both of these, just wanted the reference

**Comment by kapir** [comment]
Utvikler: @kh498 
Tester: @rikkeaas
